DROP TABLE IF EXISTS users, games, attempts;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    username  VARCHAR(64) UNIQUE                    NOT NULL,
    password VARCHAR(128)                            NOT NULL,
    role     VARCHAR(64)                            NOT NULL,
    active   BOOLEAN                              NOT NULL,
    active_game_id     BIGINT,
    CONSTRAINT pk_user PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS games
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    user_id   BIGINT                                    NOT NULL,
    puzzled_number    VARCHAR(64)                       NOT NULL,
    finished     BOOLEAN                              NOT NULL,
    CONSTRAINT pk_games PRIMARY KEY (id),
    CONSTRAINT fk_games_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS attempts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id  BIGINT                                     NOT NULL,
    user_id  BIGINT                                     NOT NULL,
    result VARCHAR(64)                                  NOT NULL,
    CONSTRAINT pk_attempts PRIMARY KEY (id),
    CONSTRAINT fk_attempts_game_id FOREIGN KEY (game_id) REFERENCES games (id),
    CONSTRAINT fk_attempts_user_id FOREIGN KEY (user_id) REFERENCES users (id)
    );

